version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile.client.dev
    image: client_dev
    container_name: client_dev
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
