version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile.client.dev
    image: chronology_client_dev
    container_name: chronology_client_dev
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - server
